In [1]:
import os
import numpy as np

In [2]:
dir_path = "C:\\Users\\HieuVu\\Desktop\\HieuVu\\LiLon\\data"

In [3]:
a = []
for folder in os.listdir(dir_path):
    dir_txt_path = os.path.join(dir_path, folder)
    for file in os.listdir(dir_txt_path):
        if '.txt' in file:
            with open(os.path.join(dir_txt_path, file)) as f:
                lines = f.readlines()
                for line in lines:
                    line = line.strip()
                    list_line = line.split(',')
                    a.append(list_line)
        break
    break

In [4]:
data_list = []

In [5]:
for i, file in enumerate(a):
    print(file)
    feature = {'temperature':file[5], 'humidity':file[6]}
    data_list.append(feature)

['4C11AE109277', '2019-11-18 12:12:0', '1574053920', '26.63', '47.23', '25.36', '51.60']
['4C11AE109277', '2019-11-18 12:15:0', '1574054100', '26.63', '47.23', '25.12', '50.84']
['4C11AE109277', '2019-11-18 12:18:0', '1574054280', '26.63', '47.23', '25.39', '50.73']
['4C11AE109277', '2019-11-18 12:21:0', '1574054460', '21.51', '40.98', '25.67', '49.77']
['4C11AE109277', '2019-11-18 12:24:0', '1574054640', '13.13', '28.50', '25.67', '50.09']
['4C11AE109277', '2019-11-18 12:27:0', '1574054820', '12.07', '31.43', '25.59', '50.65']
['4C11AE109277', '2019-11-18 12:30:0', '1574055000', '11.60', '27.40', '25.42', '51.14']
['4C11AE109277', '2019-11-18 12:33:0', '1574055180', '10.90', '25.43', '25.30', '51.24']
['4C11AE109277', '2019-11-18 12:36:0', '1574055360', '10.13', '22.93', '25.28', '51.21']
['4C11AE109277', '2019-11-18 12:39:0', '1574055540', '10.20', '23.50', '25.31', '50.95']
['4C11AE109277', '2019-11-18 12:42:0', '1574055720', '9.63', '22.87', '25.16', '51.04']
['4C11AE109277', '2019

In [6]:
data_list

[{'temperature': '25.36', 'humidity': '51.60'},
 {'temperature': '25.12', 'humidity': '50.84'},
 {'temperature': '25.39', 'humidity': '50.73'},
 {'temperature': '25.67', 'humidity': '49.77'},
 {'temperature': '25.67', 'humidity': '50.09'},
 {'temperature': '25.59', 'humidity': '50.65'},
 {'temperature': '25.42', 'humidity': '51.14'},
 {'temperature': '25.30', 'humidity': '51.24'},
 {'temperature': '25.28', 'humidity': '51.21'},
 {'temperature': '25.31', 'humidity': '50.95'},
 {'temperature': '25.16', 'humidity': '51.04'},
 {'temperature': '25.22', 'humidity': '50.83'},
 {'temperature': '25.29', 'humidity': '50.51'},
 {'temperature': '25.11', 'humidity': '50.58'},
 {'temperature': '25.09', 'humidity': '50.51'},
 {'temperature': '25.12', 'humidity': '50.26'},
 {'temperature': '25.12', 'humidity': '50.22'},
 {'temperature': '25.21', 'humidity': '50.08'},
 {'temperature': '25.19', 'humidity': '50.26'},
 {'temperature': '25.01', 'humidity': '50.35'},
 {'temperature': '24.87', 'humidity': '5

In [7]:
temperature = []
humidity = []
for feature in data_list:
    temperature.append(feature['temperature'])
    humidity.append(feature['humidity'])

In [8]:
temperature_thresh = 25.885
humidity_thresh = 59.95

In [9]:
label_dataset = []
for file in data_list:
    if (float(file['temperature']) > temperature_thresh or float(file['humidity']) > humidity_thresh):
        file.update({'label':1})
        label_dataset.append(file)
    else:
        file.update({'label':0})
        label_dataset.append(file)

In [24]:
weather_dataset = label_dataset

In [26]:
import pandas as pd

In [40]:
pandas_weather = {"temperature":[],"humidity":[],"label":[]}
for item in weather_dataset:
    norm_temperature = float(item["temperature"])/100
    pandas_weather["temperature"].append(norm_temperature)
    norm_humidity = float(item["humidity"])/100
    pandas_weather["humidity"].append(norm_humidity)
    pandas_weather["label"].append(int(item["label"]))
df = pd.DataFrame(pandas_weather)
df.to_csv("climate_weather.csv")

In [44]:
df.values

array([[0.2536, 0.516 , 0.    ],
       [0.2512, 0.5084, 0.    ],
       [0.2539, 0.5073, 0.    ],
       [0.2567, 0.4977, 0.    ],
       [0.2567, 0.5009, 0.    ],
       [0.2559, 0.5065, 0.    ],
       [0.2542, 0.5114, 0.    ],
       [0.253 , 0.5124, 0.    ],
       [0.2528, 0.5121, 0.    ],
       [0.2531, 0.5095, 0.    ],
       [0.2516, 0.5104, 0.    ],
       [0.2522, 0.5083, 0.    ],
       [0.2529, 0.5051, 0.    ],
       [0.2511, 0.5058, 0.    ],
       [0.2509, 0.5051, 0.    ],
       [0.2512, 0.5026, 0.    ],
       [0.2512, 0.5022, 0.    ],
       [0.2521, 0.5008, 0.    ],
       [0.2519, 0.5026, 0.    ],
       [0.2501, 0.5035, 0.    ],
       [0.2487, 0.5048, 0.    ],
       [0.2484, 0.505 , 0.    ],
       [0.2471, 0.504 , 0.    ],
       [0.2459, 0.5062, 0.    ],
       [0.2458, 0.5052, 0.    ],
       [0.2465, 0.5022, 0.    ],
       [0.2473, 0.5036, 0.    ],
       [0.2464, 0.505 , 0.    ],
       [0.245 , 0.5062, 0.    ],
       [0.2443, 0.5063, 0.    ],
       [0.

In [173]:
temperature_thresh = temperature_thresh/100
humidity_thresh = humidity_thresh/100

In [174]:
def selection_random_sample(X_fact, num_samples):
    np.random.seed(4)
    perm = np.random.permutation(X_fact.shape[0])
    perm = perm[:num_samples]
    new_samples = X_fact[perm, :]
    random_matrix = np.random.uniform(low=-0.2, high=0.2, size=(new_samples.shape[0], new_samples.shape[1]))
    random_binary_matrix = np.random.randint(2, size=(new_samples.shape[0], new_samples.shape[1])                                                 )
    gaussian_matrix = new_samples + random_matrix * random_binary_matrix
    return gaussian_matrix

In [179]:
D_train = df.values[:,:2]
gauss_matrix = selection_random_sample(D_train,100)
gauss_matrix

array([[0.37801958, 0.49936625],
       [0.10716422, 0.66923283],
       [0.41377351, 0.79817915],
       [0.2709    , 0.6739    ],
       [0.272     , 0.55643237],
       [0.2723    , 0.56282197],
       [0.17638201, 0.6493    ],
       [0.2712    , 0.646     ],
       [0.271     , 0.6462    ],
       [0.24955008, 0.6982613 ],
       [0.2714    , 0.81585167],
       [0.2617    , 0.70562837],
       [0.2714    , 0.6444    ],
       [0.2731    , 0.61029291],
       [0.35788079, 0.63158255],
       [0.2509    , 0.5051    ],
       [0.12134725, 0.54589838],
       [0.2664    , 0.6827    ],
       [0.271     , 0.6445    ],
       [0.16084619, 0.684     ],
       [0.2721    , 0.55698682],
       [0.27646129, 0.38950602],
       [0.25645491, 0.5026    ],
       [0.21963348, 0.82808764],
       [0.2677    , 0.6812    ],
       [0.309319  , 0.678     ],
       [0.44117405, 0.65086245],
       [0.2522    , 0.69866211],
       [0.34790011, 0.75088239],
       [0.271     , 0.6475    ],
       [0.

In [186]:
humidity_thresh

0.5995

In [187]:
temperature_thresh

0.25885

In [188]:
new_label_dataset = []
for item in gauss_matrix:
    if item[0] > temperature_thresh:
        new_label_dataset.append(1)
    else:
        new_label_dataset.append(0)

In [198]:
new_label_dataset = np.array(new_label_dataset)
new_label_dataset = new_label_dataset.reshape(100,1)
gauss_matrix.shape

(100, 2)

In [200]:
A = np.concatenate((gauss_matrix, new_label_dataset), axis = 1)
full_weather = np.concatenate((df.values, A), axis=0)

In [202]:
full_weather

array([[0.2536    , 0.516     , 0.        ],
       [0.2512    , 0.5084    , 0.        ],
       [0.2539    , 0.5073    , 0.        ],
       [0.2567    , 0.4977    , 0.        ],
       [0.2567    , 0.5009    , 0.        ],
       [0.2559    , 0.5065    , 0.        ],
       [0.2542    , 0.5114    , 0.        ],
       [0.253     , 0.5124    , 0.        ],
       [0.2528    , 0.5121    , 0.        ],
       [0.2531    , 0.5095    , 0.        ],
       [0.2516    , 0.5104    , 0.        ],
       [0.2522    , 0.5083    , 0.        ],
       [0.2529    , 0.5051    , 0.        ],
       [0.2511    , 0.5058    , 0.        ],
       [0.2509    , 0.5051    , 0.        ],
       [0.2512    , 0.5026    , 0.        ],
       [0.2512    , 0.5022    , 0.        ],
       [0.2521    , 0.5008    , 0.        ],
       [0.2519    , 0.5026    , 0.        ],
       [0.2501    , 0.5035    , 0.        ],
       [0.2487    , 0.5048    , 0.        ],
       [0.2484    , 0.505     , 0.        ],
       [0.

In [204]:
dtf = pd.DataFrame(full_weather)

In [205]:
dtf.to_csv("climate_weather.csv")

In [7]:
import pandas as pd
data = pd.read_csv("C:\\Users\\HieuVu\\Desktop\\HieuVu\\BTL_Thiet_ke_he_nhung-master\\climate_weather.csv", header=None)
data.values

array([[0.2536    , 0.516     , 0.        ],
       [0.2512    , 0.5084    , 0.        ],
       [0.2539    , 0.5073    , 0.        ],
       [0.2567    , 0.4977    , 0.        ],
       [0.2567    , 0.5009    , 0.        ],
       [0.2559    , 0.5065    , 0.        ],
       [0.2542    , 0.5114    , 0.        ],
       [0.253     , 0.5124    , 0.        ],
       [0.2528    , 0.5121    , 0.        ],
       [0.2531    , 0.5095    , 0.        ],
       [0.2516    , 0.5104    , 0.        ],
       [0.2522    , 0.5083    , 0.        ],
       [0.2529    , 0.5051    , 0.        ],
       [0.2511    , 0.5058    , 0.        ],
       [0.2509    , 0.5051    , 0.        ],
       [0.2512    , 0.5026    , 0.        ],
       [0.2512    , 0.5022    , 0.        ],
       [0.2521    , 0.5008    , 0.        ],
       [0.2519    , 0.5026    , 0.        ],
       [0.2501    , 0.5035    , 0.        ],
       [0.2487    , 0.5048    , 0.        ],
       [0.2484    , 0.505     , 0.        ],
       [0.

# Logistic Regression

In [38]:
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals
import numpy as np 
import matplotlib.pyplot as plt
np.random.seed(2)

X = np.array([[0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50, 
              2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50]])

y = np.array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

# extended data 
X = np.concatenate((np.ones((1, X.shape[1])), X), axis = 0)
print(X)
print(y.shape)

[[1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
  1.   1.   1.   1.   1.   1.  ]
 [0.5  0.75 1.   1.25 1.5  1.75 1.75 2.   2.25 2.5  2.75 3.   3.25 3.5
  4.   4.25 4.5  4.75 5.   5.5 ]]
(20,)


In [39]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [40]:
def logistic_sigmoid_regression(X, y, w_init, eta, tol = 1e-4, max_count = 10000):
    w = [w_init]    
    it = 0
    N = X.shape[1]
    d = X.shape[0]
    count = 0
    check_w_after = 20
    while count < max_count:
        # mix data 
        mix_id = np.random.permutation(N)
        for i in mix_id:
            xi = X[:, i].reshape(d, 1)
            yi = y[i]
            zi = sigmoid(np.dot(w[-1].T, xi))
            w_new = w[-1] + eta*(yi - zi)*xi
            count += 1
            # stopping criteria
            if count%check_w_after == 0:                
                if np.linalg.norm(w_new - w[-check_w_after]) < tol:
                    return w
            w.append(w_new)
    return w

In [41]:
eta = .05 
d = X.shape[0]
print("d:",d)
w_init = np.random.randn(2, 1)
print("w_init",w_init)
w = logistic_sigmoid_regression(X, y, w_init, eta)
w[-1]

d: 2
w_init [[-0.41675785]
 [-0.05626683]]


array([[-4.092695  ],
       [ 1.55277242]])

In [42]:
sigmoid(np.dot(w[-1].T, X))

array([[0.03501592, 0.05078108, 0.07310642, 0.10416972, 0.14634799,
        0.20175793, 0.20175793, 0.27147534, 0.35458234, 0.4475032 ,
        0.54424128, 0.63775242, 0.72188183, 0.79282004, 0.89267823,
        0.92460236, 0.94758783, 0.96384008, 0.97518471, 0.9884283 ]])

In [43]:
X

array([[1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
        1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ],
       [0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 1.75, 2.  , 2.25, 2.5 , 2.75,
        3.  , 3.25, 3.5 , 4.  , 4.25, 4.5 , 4.75, 5.  , 5.5 ]])

In [44]:
y

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

In [51]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X.T, y)
clf.predict_proba(X.T)
clf.predict(X.T)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

data = pd.read_csv("data_classification.csv", header = None)


In [37]:
D_train = []
D_test = []
for ele in data.values:
    D_train.append(ele[:2])
    D_test.append(ele[-1])
D_train = np.asarray(D_train)
D_test = np.asarray(D_test)

In [40]:
X_train, X_test, y_train, y_test = train_test_split(D_train, D_test, test_size=0.3, random_state=42)

In [43]:
X_train

array([[8.54042132, 2.59037423],
       [7.86385017, 7.72638337],
       [6.77931871, 2.02818075],
       [1.85911241, 5.69186756],
       [6.46089606, 7.07629269],
       [1.9222695 , 1.33142726],
       [0.45567818, 4.72229748],
       [9.08162719, 1.4373504 ],
       [7.87439057, 7.79109336],
       [9.43820269, 1.94381244],
       [7.46436788, 9.94517621],
       [0.92562818, 3.42126711],
       [6.63560308, 8.54280268],
       [0.02227957, 2.65842789],
       [4.52961874, 4.90551154],
       [1.54910163, 9.37513216],
       [9.68310414, 9.50704973],
       [1.19638318, 7.47574486],
       [0.86040708, 8.98818814],
       [9.18129712, 0.17147465],
       [1.04321284, 2.60976512],
       [7.15095484, 3.89942042],
       [4.35755102, 9.88798331],
       [5.09102909, 9.87313409],
       [7.67235895, 5.41639979],
       [3.44310934, 7.06634686],
       [8.97821589, 0.99343751],
       [7.51730898, 2.24892929],
       [8.34775105, 1.86081251],
       [0.20005787, 4.83405955],
       [7.

NameError: name 'X' is not defined

In [54]:
X = np.random.rand(70,3)
y = np.random.rand(70,1)
z = np.random.rand(70,)
X.T.shape

(3, 70)

In [53]:
gradient = np.dot(X.T, (y -z))
gradient

array([[-3.39577501],
       [-1.51332311],
       [-0.93057337]])

In [56]:
z.reshape((70,1)).shape

(70, 1)

In [61]:
def sigmoid(z):
    return 1.0 / ( 1 + np.exp(-z))
def predict_proba(feature, weight):
    z = np.dot(feature, weight)
    return sigmoid(z)

In [62]:
X = np.array([1, 2.23818, 4.53484])
Y = np.array([[0.95366],[0.4993],[0.92481]])

predict_proba(X,Y)

array([0.99810199])